version: '3'

services:
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "ninja_spring_database"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  pgdata:
